### ISSUE TITLE
yak for Illumina data?

### ISSUE THREAD

**Issue by baozg** [Nextomics/NextPolish2#1]
Hi, @moold 

Is the `yak` take the HiFi kmer or Illumina kmer? In the code, it was from `sr.R*.fq.gz`, but the documentation didn't mention. So this could be from the short reads or HiFi reads?

**Comment by moold** [comment]
Illumina kmer

**Comment by baozg** [comment]
Thanks for your prompt response.

**Comment by baozg** [comment]
Could this work on the hifi-only?

**Comment by moold** [comment]
No
