### ISSUE TITLE
job killed

### ISSUE THREAD

**Issue by yeeus** [Nextomics/NextPolish2#10]
I used nextpolish2 to polish a few genomes several days ago. When I looked the log file today, I found this report in some jobs:
`/var/spool/slurm/d/job1113564/slurm_script: line 31: 37987 Killed                  nextPolish2 -t ${threads} -r ${mat_HiFi_mapping_file} ${mat_asm} $k21 $k31 -o ${mat_asm}.np2.fasta`

and in the initial jobs which were run in the first few days, there was all right about the polishing process.
Best wishes!

**Comment by moold** [comment]
This usually caused by RAM, so try to reduce threats to reduce RAM usage.

**Comment by yeeus** [comment]
Thanks!
I will have a try!
