### ISSUE TITLE
Correction of haplotypes

### ISSUE THREAD

**Issue by monian1113** [Nextomics/NextPolish2#11]
If I am using haplotype assembly with hifiasm via hic data instead of trio data, will NextPolish2 be able to do haplotype aware error correction, and what should I do in this case?

**Comment by moold** [comment]
Yes, just follow the usage docs, no extra steps.

**Comment by monian1113** [comment]
> Yes, just follow the usage docs, no extra steps.

Should I combine hap1 and hap2 for reads mappimg, or first isolate the reads that match hap1 or hap2 separately and then correct each haplotype separately?

**Comment by moold** [comment]
I suggest mapping and correcting each haplotype separately.
BTW you can also try both strategies to see which one is better.
