### ISSUE TITLE
which asm.fa should be used in nextpolish2? the contig.fa or genome.fa

### ISSUE THREAD

**Issue by QianghuiZhu** [Nextomics/NextPolish2#15]
Hi! NextPolish2 is a great software for correcting errors.
I have poor knowledges about assembly. And I want to know which asm.fa should be used in nextpolish2?
I run hifiasm and got contig.fa. And after running juicer and 3d-dna, I got the genome.fa. May I use genome.fa directly in nextpolish2? Or maybe should I use contig.fa with nextpolish2 first, then run juicer and 3d-dna, and fix the genome.fa with nextpolish2 again?
Thanks!

**Comment by moold** [comment]
`genome.fa` is OK.

**Comment by QianghuiZhu** [comment]
OK.
Thanks for this!
