### ISSUE TITLE
Genome gets smaller after correction

### ISSUE THREAD

**Issue by Bank-tidy** [Nextomics/NextPolish2#16]
Hello author, I tried to use your software to correct two genomes again, and the genomes became smaller. What is the reason? In theory, can't it only correct SNPs and indels?

These are my codes:
```
minimap2 -ax map-hifi -t 60 LC_filled_N0.fasta /public1/home/yinhang/projects/two_genomes/01_data/HiFi_fastq/LC.ccs.fq|samtools sort -o LC.sort.bam -
samtools index LC.sort.bam

yak count -o k21_ngs.yak -k 21 -b 37 NGS_correct_1.fq.gz NGS_correct_2.fq.gz
yak count -o k31_ngs.yak -k 31 -b 37 NGS_correct_1.fq.gz NGS_correct_2.fq.gz

nextPolish2 -t 60 LC.sort.bam LC_filled_N0.fasta k21_ngs.yak k31_ngs.yak > LC_corrected_N0.fa
```

![image](https://github.com/Nextomics/NextPolish2/assets/108465040/2cd3f9fd-ae3d-4d50-b33b-48d866c0371e)
![image](https://github.com/Nextomics/NextPolish2/assets/108465040/336d7e65-305a-4bd2-86f5-fecef1cb348f)

**Comment by Marison-1** [comment]
> Hello author, I tried to use your software to correct two genomes again, and the genomes became smaller. What is the reason? In theory, can't it only correct SNPs and indels?
> 
> These are my codes:
> 
> ```
> minimap2 -ax map-hifi -t 60 LC_filled_N0.fasta /public1/home/yinhang/projects/two_genomes/01_data/HiFi_fastq/LC.ccs.fq|samtools sort -o LC.sort.bam -
> samtools index LC.sort.bam
> 
> yak count -o k21_ngs.yak -k 21 -b 37 NGS_correct_1.fq.gz NGS_correct_2.fq.gz
> yak count -o k31_ngs.yak -k 31 -b 37 NGS_correct_1.fq.gz NGS_correct_2.fq.gz
> 
> nextPolish2 -t 60 LC.sort.bam LC_filled_N0.fasta k21_ngs.yak k31_ngs.yak > LC_corrected_N0.fa
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/108465040/318014751-2cd3f9fd-ae3d-4d50-b33b-48d866c0371e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDc1OTksIm5iZiI6MTcxMTcwNzI5OSwicGF0aCI6Ii8xMDg0NjUwNDAvMzE4MDE0NzUxLTJjZDNmOWZkLWFlM2QtNGQ1MC1iMzNiLTQ4ZDg2NmMwMzcxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMDE0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWJlZDRiYzk5MDg2YzkwNGY2NjE2MmZkY2UyYzhiZTViNjljNzhmNjc5ZWE3M2UxNzM0NGMyOTk4M2FjMzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NCAE8aL_CJmATs5TfLsvSdLjtsrbEe7VBRyzHK2m0kg) ![image](https://private-user-images.githubusercontent.com/108465040/318014777-336d7e65-305a-4bd2-86f5-fecef1cb348f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDc1OTksIm5iZiI6MTcxMTcwNzI5OSwicGF0aCI6Ii8xMDg0NjUwNDAvMzE4MDE0Nzc3LTMzNmQ3ZTY1LTMwNWEtNGJkMi04NmY1LWZlY2VmMWNiMzQ4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMDE0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTc2YTlmNDYwM2VjZjc3YmI0ZTNjMmM1OWFlNDAxOWI2Mzk5MmMyODliZGRlNjBiZDVmZGE3MDk1M2U2MThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2mocC4Py_g6FJt8sGk5bPZA026C8walsV7MIkdriW9E)

I met the same problem as you. I polished 5 assembly use this tool, and each of them smaller 1~4Mb than before and reference.
Maybe it's reasonable,but I expect the author for a professional explaination.

**Comment by moold** [comment]
It feels like there's something wrong, the genome size shouldn't change too much, Does the corrected genome have the same number sequence as the original ref? Could you share the detailed statistics to here?

**Comment by Bank-tidy** [comment]
> It feels like there's something wrong, the genome size shouldn't change too much, Does the corrected genome have the same number sequence as the original ref? Could you share the detailed statistics to here?

Not change too much ,still 12 sequencs, from 1096.96 Mb to 1096.71 Mb. Changed about 250 Kb, is it reasonable?

![image](https://github.com/Nextomics/NextPolish2/assets/108465040/fbc7ae37-9570-45a8-b7b9-8f177cf998bd)

**Comment by Bank-tidy** [comment]
> It feels like there's something wrong, the genome size shouldn't change too much, Does the corrected genome have the same number sequence as the original ref? Could you share the detailed statistics to here?

Detail changes are as follows:
group1 132785395 -> 132718027
group2 114892731 -> 114887727
group3 103262822 -> 103224677
group4 100419264 -> 100413931
group5 99907961 -> 99907504
group6 93758231 -> 93727397
group7 93135190 -> 93092808
group8 88913125 -> 88895220
group9 87091357 -> 87077464
group10 85308775 -> 85298291
group11 76449378 -> 76436882
group12 74317084 -> 74304218

Looking forward to your reply

**Comment by moold** [comment]
I did some tests but didn't get the result that the genome size changed much, so coulld you extract the sequence and bam file of`group7`, and  `k21_ngs.yak k31_ngs.yak`, and share me these files? BTW, this should be caused by some heterozygous long insertion or deletion variations.

**Comment by Bank-tidy** [comment]
> I did some tests but didn't get the result that the genome size changed much, so coulld you extract the sequence and bam file of`group7`, and `k21_ngs.yak k31_ngs.yak`, and share me these files? BTW, this should be caused by some heterozygous long insertion or deletion variations.

Of course! But is there any good way to share it (totally aboout 15G) with you? I’m in China.

**Comment by Bank-tidy** [comment]
> I did some tests but didn't get the result that the genome size changed much, so coulld you extract the sequence and bam file of`group7`, and `k21_ngs.yak k31_ngs.yak`, and share me these files? BTW, this should be caused by some heterozygous long insertion or deletion variations.

The heterozygosity rate of my sample is indeed a bit high, and the assembled genome may be larger than expected. In this case, are the corrected results credible?Thank you!

**Comment by moold** [comment]
You can map the corrected genome to the original reference genome and see where the long changes caused by "NextPolish2" are, and then check the bam file for those changed regions.

**Comment by moold** [comment]
We have released a new version with a new option `--max_indel_len`, you can try it to see if it can solve this problem.
