### ISSUE TITLE
Polishing by HiFi data to draft assembly made of CLR data.

### ISSUE THREAD

**Issue by Jung19911124** [Nextomics/NextPolish2#18]
I am involved in a genome project for a wild animal species with a huge genome (6.5 Gb). We expect the genome to be highly heterozygous, and perhaps over half of it will be repetitive sequences. 

Due to budget constraints, we could only obtain x80 coverage of CLR, x20 of Hifi data, and x150 of short-read data. I plan to use CLR to make draft assembly and then use HiFi. 
Would it be effective to use HiFi data in Nextpolish2 for policing against the draft assembly made with CLR?

Any suggestions would be appreciated.

**Comment by moold** [comment]
Yes.

**Comment by moold** [comment]
Is the sample of short-read data the same as the sample of HiFi?

**Comment by Jung19911124** [comment]
No, short read data was from the same indivdual of CLR.

**Comment by moold** [comment]
So I don't suggest to use `NextPolish2` in this case, you can use [NextPolish](https://github.com/Nextomics/NextPolish)

**Comment by Jung19911124** [comment]
Thanks. 
I will try NextPolish.
