### ISSUE TITLE
two phased haplotypes questions

### ISSUE THREAD

**Issue by Lin-Yuying** [Nextomics/NextPolish2#19]
Hi Jiang,

Thank you so much for developing this fantastic tool. 

In your example, you used an asm.fa. However, with hifiasm, it yields two phased haplotypes. In this scenario, what would be the recommended approach to rectify switch errors in both haplotypes? Should I run the NextPolish2 pipeline separately for each haplotype?

Thanks in advances! 

Best,
Lin

**Comment by moold** [comment]
If your genome is assembled via trio binning. You can discard reads that have different haplotype with the reference before the mapping procedure. 
If not, just use all reads to do mapping and  the default parameters, It will maintain the same haplotype as ref.
