### ISSUE TITLE
:Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', src/main.rs:1695:51

### ISSUE THREAD

**Issue by Hanjiangna** [Nextomics/NextPolish2#22]
hello 
my code
nextPolish2 -r hifi.map.sort.bam sam.fa k21.yak k31.yak >asm.np2.fa
error
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }', src/main.rs:1695:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by moold** [comment]
It seems `sam.fa` is empty?

**Comment by Hanjiangna** [comment]
sorry, it is empty . I've just realized it's an empty file, whereas it wasn't before. Thank you very much for your prompt response.
