### ISSUE TITLE
Why no any improvement of QV is achieved using NextPolish2?

### ISSUE THREAD

**Issue by bioinformaticspcj** [Nextomics/NextPolish2#3]
Dear the authors,

Thanks for developing such a useful tool to polish the results of Hifiasm. I try to polish my Hifiasm's assembly (assembled with 40 × hifi reads) but found the QV  of the polished assembly is as the same as the unpolished one.  The species genome is highly heterozygous (rate: 0.77%). I do not know why? Could you be kind to help me?

The commands used are as follows:
hifiasm -t 60 -o Pvat -l 2 -s 0.75 --h1 R1.fq.gz --h2 R2.fq.gz hifi.fastq.gz
winnowmap -k 21 -t 100 -W repetitive_k21.txt -ax map-pb Pvat.hic.p_ctg.fa hifi.fastq.gz |samtools sort -@ 100 -o hifi.map.sort.bam -
yak count -t 100 -o k21.yak -k 21 -b 37 <(zcat illumina_*.fq.gz)
yak count -t 100 -o k31.yak -k 31 -b 37 <(zcat illumina_*.fq.gz)
nextPolish2 -r hifi.map.sort.bam Pvit.hic.p_ctg.fa k21.yak k31.yak -t 100 -o Pvat.hic.p_ctg.polished.v1.fa

The QV before polishing:
45.1437

The QV after polishing:
45.1451

Thanks again!
Bob

**Comment by moold** [comment]
Could you share the raw data (assembly.fa illumina_.fq.gz  hifi.fastq.gz) to me? so I can figure out why?
In addition, you can map the illumina reads to the assembly, and then inspect the mapping coverage/quality of the error kmer in the assembly.

**Comment by bioinformaticspcj** [comment]
Thanks for your timely reply.
Given the illumina_R*.fq.gz files and the&nbsp;hifi.fastq.gz file are too big (in total more than 100Gb in size), I am afraid I could not share the files with you. I will try to see how the short reads map the assembly and provide you with the results soon.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nextomics/NextPolish2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 中午1:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nextomics/NextPolish2] Why no any improvement of QV is achieved using NextPolish2? (Issue #3)





 
Could you share the raw data (assembly.fa illumina_.fq.gz  hifi.fastq.gz) to me? so I can figure out why?
 In addition, you can map the illumina reads to the assembly, and then inspect the mapping coverage/quality of the error kmer in the assembly.

**Comment by moold** [comment]
OK

**Comment by bioinformaticspcj** [comment]
Dear the author,


I have checked the illumina reads and the error kmers by mapping the reads to the assembly. The results showed about 49% of error kmers have no reads covered and only about 0.05% error kmers have &gt; 10 ×reads covered with MAQ&gt; 10. Do the results indicate the reads are of low quality and can not be used to polish the assembly?


Thanks&nbsp;
Bob




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nextomics/NextPolish2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nextomics/NextPolish2] Why no any improvement of QV is achieved using NextPolish2? (Issue #3)





 
OK

**Comment by moold** [comment]
No, but the  improvement will not be great.  becasue nextPolish2 will keep ref. unchanged if it cannot confirm that the candidate kmer is correct to avoid potential overcorrections, BTW: You can use PCR-free library.

**Comment by bioinformaticspcj** [comment]
Thanks for your valuable advice,
&nbsp;
I have a question that if I could use MGI reads to correct the kmer? MGI reads are all sequenced using PCR-free library.


Best,
Bob


------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Nextomics/NextPolish2"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, May 9, 2023 04:50 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Nextomics/NextPolish2] Why no any improvement of QV is achieved using NextPolish2? (Issue #3)





 
No, but the  improvement will not be great.  becasue nextPolish2 will keep ref. unchanged if it cannot confirm that the candidate kmer is correct to avoid potential overcorrections, BTW: You can use PCR-free library.

**Comment by wangsb111** [comment]
@bioinformaticspcj   hello,  did you resolved this  problem now?  i met the same problem.

**Comment by moold** [comment]
You need to first check the mapping coverage/quality in the regions of the assembly with error kmers. If these regions has no short reads mapped, NextPolish2 can not be used to improve QV.

**Comment by wangsb111** [comment]
@bioinformaticspcj  did you got the QV by nextpolish2 or the merqury ?
