### ISSUE TITLE
ONT assembly Polishing

### ISSUE THREAD

**Issue by ufaroooq** [Nextomics/NextPolish2#30]
Hi,

I have Nanopore sequeunce data for some fungal sample.
I have already De novo assemblies using **NextDenovo** with nanopore raw data.
Other than that I have High quality Illumina PE 150bp data for same samples.

As the fungal genomes are repetative, 

1. **Should i use NextPolish or NextPolish2 for polishing of these assemblies.**
2. Should i also run multiple rounds like ist donr with Racon or Pilon when using both Nanopore and Illumina fastqs as input togather ?

thanks

**Comment by moold** [comment]
you can use `NextPolish` and see [here](https://nextpolish.readthedocs.io/en/latest/TUTORIAL.html#polishing-using-short-reads-and-long-reads) for an example.
