### ISSUE TITLE
Memory allocation failure while running nextPolish2 for genome polishing

### ISSUE THREAD

**Issue by sunjinkkk** [Nextomics/NextPolish2#31]
Hi,

I encountered a memory allocation error when polishing a ~700Mb genome using nextPolish2. Despite trying multiple suggestions from previous Issues, such as polishing single chromosomes and reducing the number of threads to 1, the error persists. Below is the error message and relevant code:

Error Message:
```
memory allocation of 10 bytes failed  
/opt/gridview/slurm/spool/slurmd/job1270389/slurm_script: line 17: 31238 Aborted (core dumped) nextPolish2 -t 1 hifi.map.sort.bam genome.fa k21.yak k31.yak > asm.np2.fa
```

System Info:
SLURM Job script with 1 thread and 500G memory 

Data and Code:
Data:
Genome size: ~700Mb
Hifi data: 50X
NGS data: 50X

Here is the code I used for preparing the input and running nextPolish2:
```bash
source ~/software/miniforge/etc/profile.d/conda.sh
conda activate nextpolish

meryl count k=15 output merylDB genome.fa
meryl print greater-than distinct=0.9998 merylDB > repetitive_k15.txt
winnowmap -t 30 -W repetitive_k15.txt -ax map-pb genome.fa hifi.fa | samtools sort -o hifi.map.sort.bam -
samtools index hifi.map.sort.bam

yak count -o k21.yak -k 21 -b 37 <(zcat sr_clean_R*.fq.gz) <(zcat you_clean_R*.fq.gz)
yak count -o k31.yak -k 31 -b 37 <(zcat sr_clean_R*.fq.gz) <(zcat you_clean_R*.fq.gz)

nextPolish2 -t 1 hifi.map.sort.bam genome.fa k21.yak k31.yak > asm.np2.fa
```

Is there a known solution for this error, or can you suggest any further debugging steps?

Thank you in advance for your assistance!

Best,
Jin

**Comment by moold** [comment]
could you run nextPolish2 with `/usr/bin/time -v nextPolish2 -t 1 hifi.map.sort.bam genome.fa k21.yak k31.yak > asm.np2.fa` and paste the log to here?

**Comment by sunjinkkk** [comment]
I followed your suggestion to run nextPolish2 with ```/usr/bin/time -v``` to collect detailed resource usage information. Below is the complete log of the run:
```
memory allocation of 10 bytes failed
Command terminated by signal 6
	Command being timed: "nextPolish2 -t 1 hifi.map.sort.bam rechr.fa k21.yak k31.yak"
	User time (seconds): 59.21
	System time (seconds): 5.69
	Percent of CPU this job got: 100%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:04.76
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 13199760
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 3883640
	Voluntary context switches: 91
	Involuntary context switches: 24
	Swaps: 0
	File system inputs: 495104
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by moold** [comment]
Could you install NextPolish2 by source and try again ? 
see `Installing from source ` section.

**Comment by sunjinkkk** [comment]
Thank you for your suggestion. I installed NextPolish2 from source and switched to a workstation with 24 cores and 192 GB of RAM. The program is now running successfully. I appreciate your help!
