### ISSUE TITLE
thread '<unnamed>' panicked at src/main.rs:1576:22:

### ISSUE THREAD

**Issue by yaoyuan0729** [Nextomics/NextPolish2#32]
An error occurred during the second round of polishing：
thread '<unnamed>' panicked at src/main.rs:1576:22:
attempt to divide by zero
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by moold** [comment]
Could you use `samtools` to extract the contig sequence that caused this error and the corresponding bam file and send it to me so that I can debug it?

**Comment by yaoyuan0729** [comment]
> Could you use `samtools` to extract the contig sequence that caused this error and the corresponding bam file and send it to me so that I can debug it?

I think it was np2 that disrupted the scaffold order during the first round of polishing. After I reordered the scaffolds and ran it again, the error did not occur.

**Comment by yaoyuan0729** [comment]
> 我想知道您是否根据更正后的基因组重新映射了读数？第一次更正后。你应该做 re-map。

Yes, I performed the re-map.
