### ISSUE TITLE
Install nextpolish2 with conda

### ISSUE THREAD

**Issue by guianrey** [Nextomics/NextPolish2#36]
Dear

"I have installed NextPolish2 with Conda, but when I try to run the program, it says 'Illegal Instruction". 
![image](https://github.com/user-attachments/assets/6c2228e8-6830-4465-a421-f09851dc33f5)

![image](https://github.com/user-attachments/assets/54703796-1307-4a31-a235-70cfda7b4eeb)

Best

Guillermo

**Comment by moold** [comment]
try install with source, see [here](https://github.com/Nextomics/NextPolish2?tab=readme-ov-file#installing-from-source)

**Comment by xusheng-code** [comment]
$ git clone --recursive git@github.com:Nextomics/NextPolish2.git
Cloning into 'NextPolish2'...
The authenticity of host 'github.com (20.205.243.166)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,20.205.243.166' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

**Comment by xusheng-code** [comment]
> $ git clone --recursive [git@github.com](mailto:git@github.com):Nextomics/NextPolish2.git Cloning into 'NextPolish2'... The authenticity of host 'github.com (20.205.243.166)' can't be established. ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM. Are you sure you want to continue connecting (yes/no/[fingerprint])? yes Warning: Permanently added 'github.com,20.205.243.166' (ECDSA) to the list of known hosts. [git@github.com](mailto:git@github.com): Permission denied (publickey). fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.


Haha，I overcame this bug through establishing a new environment, then nextpolish2 can be installed by conda.
