### ISSUE TITLE
thread '<unnamed>' panicked at 'byte index 11129 is out of bounds of ...

### ISSUE THREAD

**Issue by yeeus** [Nextomics/NextPolish2#7]
我按照

> https://github.com/Nextomics/NextPolish2/blob/main/doc/benchmark3.md

这个网址的教程对我trio binning后的父母本进行polish。以下是报错：
`thread '<unnamed>' panicked at 'byte index 11129 is out of bounds of TTGCTTCTTTGACCAAAACACCACCTTATGACATTGGTTCTCCAAATCTTATGTCCTTCTGACATACAAAATACTACACAATGTCATATCATTCTATGTCAATAGTTCCCAAAAGTCTTAACTTGTTCCAGCATCAACTCTAAAGTCCAAAGTTTCATCTGAGATTCAAGGCAAGTTCCTTTCAGCTATGAGCCTTTAGGATCAATAAAAATTTATTTACTTTCAAGATACAATGATTTTGCAAGCATTGGGTAAA[...], src/main.rs:409:36
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
/var/spool/slurm/d/job1102999/slurm_script: line 39: 88136 Aborted                 (core dumped) nextPolish2 -r ${mat_HiFi_mapping_file} ${mat_asm} $k21 $k31 -o ${mat_asm}.np2.fasta`
其中`mat_HiFi_mapping_file=au_po_mat/racon_mat.meryl.iter_2.winnowmap.sorted.bam`（因为我看到教程里的似乎只是比对了一下，用的并不是racon polish之后再比对的文件，所以我多迭代了一轮，用了第二轮的bam文件）

线程的话，我一开始是20，后面改成5，这里是1，都会报这个错。

**Comment by moold** [comment]
Please use the bam file produced by the first iteration.

**Comment by yeeus** [comment]
@moold thank you!
And what I want to say is how about the threads? Are they must be less 5?

**Comment by moold** [comment]
no
