### ISSUE TITLE
memory allocation failed

### ISSUE THREAD

**Issue by Ne0tea** [Nextomics/NextPolish2#8]
Hi！
I was tring to polish a genome with 1.3g at a node with 2T memory, but constantly got the error of "memory allocation of xxx bytes failed". According to your previous recommendation, I decraesed `-t` to 1, and it failed. Then, I split my genome and bam file, while it turns out the same error.
Could you please your comments?

**Comment by moold** [comment]
Can you download the latest version and try again? If still have this error? Can you paste the full error message here?

**Comment by Ne0tea** [comment]
Thanks for your comment!
The error message is 
`Starting
Wed Aug  2 21:37:35 CST 2023
node21
memory allocation of 835916608 bytes failed
/opt/gridview//pbs/dispatcher/mom_priv/jobs/42661.tc6000.SC: line 19: 371102 Aborted                 (core dumped) ~/software/next_polish2/target/release/next_polish2 -t 20 -r $bam $asm ${yak1} $yak2 > ${asm%.*}_gfa_chr_np2.fa
Finished
`
`Starting
Wed Aug  2 13:49:00 CST 2023
node21
memory allocation of 835916608 bytes failed
/opt/gridview//pbs/dispatcher/mom_priv/jobs/42634.tc6000.SC: line 19: 373261 Aborted                 (core dumped) ~/software/next_polish2/target/release/next_polish2 -t 1 -r $bam $asm ${yak1} $yak2 > ${asm%.*}_gfa_chr_np2.fa
Finished
`
and nextpolish2 version is 
![1691075451128](https://github.com/Nextomics/NextPolish2/assets/113273372/beff3cd5-d3e4-4b6a-b71c-a2e288209c4d)

**Comment by moold** [comment]
Did you run the test data successfully?

**Comment by Ne0tea** [comment]
![image](https://github.com/Nextomics/NextPolish2/assets/113273372/9e05c9ed-e96a-451a-a879-6052abcd0c92)
yeah, it is successful with test data.

**Comment by Marison-1** [comment]
> Thanks for your comment! The error message is `Starting Wed Aug 2 21:37:35 CST 2023 node21 memory allocation of 835916608 bytes failed /opt/gridview//pbs/dispatcher/mom_priv/jobs/42661.tc6000.SC: line 19: 371102 Aborted (core dumped) ~/software/next_polish2/target/release/next_polish2 -t 20 -r $bam $asm ${yak1} $yak2 > ${asm%.*}_gfa_chr_np2.fa Finished ` `Starting Wed Aug 2 13:49:00 CST 2023 node21 memory allocation of 835916608 bytes failed /opt/gridview//pbs/dispatcher/mom_priv/jobs/42634.tc6000.SC: line 19: 373261 Aborted (core dumped) ~/software/next_polish2/target/release/next_polish2 -t 1 -r $bam $asm ${yak1} $yak2 > ${asm%.*}_gfa_chr_np2.fa Finished ` and nextpolish2 version is ![1691075451128](https://private-user-images.githubusercontent.com/113273372/258155727-beff3cd5-d3e4-4b6a-b71c-a2e288209c4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDcxMTUsIm5iZiI6MTcxMTcwNjgxNSwicGF0aCI6Ii8xMTMyNzMzNzIvMjU4MTU1NzI3LWJlZmYzY2Q1LWQzZTQtNGI2YS1iNzFjLWEyZTI4ODIwOWM0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxMDA2NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTQwZjhiZWUzZjE2MjdlYTU3MjMwNWZhMzM3NDY5Nzg5NDE2YTJkMGYwZGQzOGFjNjI4MTEzNTk1YzgyYjk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4nV7Sz1KFWB_P4fB75FC1XrgRJXQT03OXtXPRjQFRME)

this tools may has a high resource consumption, I met the same problem as you, so I separate the Chr into different file and run them again in a separate way, it worked well

**Comment by Ne0tea** [comment]
> p

Thanks for your reply, I relize
