### ISSUE TITLE
Installed issue

### ISSUE THREAD

**Issue by JhinAir** [Nextomics/NextPolish2#9]
Hi,

I got the error: failed to run custom build command for `libz-sys v1.1.12`, when run installion with 'cargo build --release'.
![image](https://github.com/Nextomics/NextPolish2/assets/28035521/680d74a0-4aea-47e8-869d-a2391d3b0c4f)
Do you have any ideas? Thank you!

Jing

**Comment by moold** [comment]
It seems that this is a bug caused by libz-sys, but it has been fixed, so you can re-download NextPolish2 and reinstall it.

**Comment by JhinAir** [comment]
Hi, I was using the latest v0.2.0, and it got this error. I tried again with the same error. More hints please? thank you.

**Comment by moold** [comment]
Did you delete the entire `NextPolish2` directory and download it again?

**Comment by JhinAir** [comment]
yes, I have.

**Comment by moold** [comment]
I think you can try adding `libz-sys = "1.1.0"` to the next line of `[dependencies]` from the file `Cargo.toml` file. 
If it still reports errors, you can change `1.1.0` to other version.

BTW: I'm not sure if it works, but you can have a try
